#!/bin/bash

# AoC is EST.
export TZ=EST

# Run for Advent
while mm=$(date +%m) dd=$(date +%d); md=${mm}${dd}; (( md >= 1130 && md <= 1225 )); do
	# Wait for EST midnight
	sleep $(( $(date -d '12am tomorrow' +%s) - $(date +%s) + 1)) 
	# Set up the puzzle
	dd=$(date +%d)
	echo "Day $dd"
	./setup "$dd"
done
