#!/bin/bash

# TODO: Convert to Python
# Merge in the codeblocks code
# Pandoc the HTML -> MD
# Auto sleep and compute date
# --sleep flag -- sleep until midnight EST and open vim after fetching
# Optional --date YYYYDD or auto compute

if (( $# != 1 )); then
  echo 'Bad usage'
  exit 1
fi
printf -vnum '%02d' "$1"

if [[ ! -f "py/$num.py" ]]; then
  sed "s/NN/$num/" py/tmpl.py > "py/$num.py"
  ./codeblocks.py "$1" >> "py/$num.py"
  printf '# v''im:ts=2:sw=2:expandtab\n' >> "py/$num.py"
fi
chmod 700 "py/$num.py"

[[ ! -f "data/$num.txt" ]] && wget --header "$(< ~/.xdg/data/aoc.2020.cookie)" --output-document="data/$num.txt" "https://adventofcode.com/2020/day/$1/input"
