#!/bin/bash

# TODO: Convert to Python
# Merge in the codeblocks code
# Pandoc the HTML -> MD
# Auto sleep and compute date
# --sleep flag -- sleep until midnight EST and open vim after fetching
# Optional --date YYYYDD or auto compute

[[ $YEAR ]] || { echo 'Set $YEAR.'; exit 1; }

if (( $# != 1 )); then
  echo 'Bad usage'
  exit 1
fi
printf -vnum '%02d' "$1"

if [[ ! -f "$YEAR/$num.py" ]]; then
  sed "s/NN/$num/" $YEAR/tmpl.py > "$YEAR/$num.py"
  ./codeblocks.py "$1" >> "$YEAR/$num.py"
  printf '# v''im:ts=2:sw=2:expandtab\n' >> "$YEAR/$num.py"
fi
chmod 700 "$YEAR/$num.py"

[[ ! -f "$YEAR/data/$num.txt" ]] && wget --header "$(< ~/.xdg/data/aoc.2020.cookie)" --output-document="$YEAR/data/$num.txt" "https://adventofcode.com/$YEAR/day/$1/input"
