"""Everyone Codes Day N."""

import collections.abc
import itertools
from lib import helpers
from lib import parsers


def solve(part: int, data: str) -> int:
    """Solve the parts."""
    pos = data.coords["@"].copy().pop()
    starts = data.coords["@"]
    bones = data.coords["#"]
    seen = {pos}
    count = 0
    dirs = [(0, -1), (1, 0), (0, 1), (-1, 0)]  # up, right, down, left

    def neighbors(pos: tuple[int, int]) -> collections.abc.Iterable[tuple[int, int]]:
        """Get the neighbors of a position."""
        return {(pos[0] + move[0], pos[1] + move[1]) for move in dirs}

    def next_position() -> collections.abc.Iterable[tuple[int, int]]:
        """Generate next positions. Closure over pos and seen."""
        # Turns UP, RIGHT, ... in UP, UP, UP, RIGHT, RIGHT, RIGHT, ...
        repeats = 1 if part < 3 else 3
        for move in itertools.cycle(i for j in dirs for i in [j] * repeats):
            next_pos = pos[0] + move[0], pos[1] + move[1]
            if next_pos not in seen:
                yield next_pos

    positions = next_position()

    if part == 1:
        end = bones.pop()
        # Count steps to get to the end bone.
        while pos != end:
            pos = next(positions)
            seen.add(pos)
            count += 1
        return count

    min_x, max_x = data.min_x, data.max_x
    min_y, max_y = data.min_y, data.max_y

    # Parts 2, 3: do not move into locations with bone.
    seen.update(bones)

    def floodfill(pos: tuple[int, int]) -> set[tuple[int, int]]:
        """Return the set of positions which are entirely surrounded."""
        todo = [pos]
        flooded = set()
        done = {pos}
        while todo:
            pos = todo.pop()
            # Stop if we get move further than the explored board, ie this is not surrounded.
            if not (min_x <= pos[0] <= max_x and min_y <= pos[1] <= max_y):
                return set()
            flooded.add(pos)
            for next_pos in neighbors(pos):
                if next_pos in done or next_pos in seen:
                    continue
                done.add(next_pos)
                todo.append(next_pos)
        return flooded

    # Want to surround the bones.
    want = {n for bone in bones for n in neighbors(bone)}
    # Exclude positions entirely surrounded by bones. We cannot reach there.
    filled = set()
    for w in want:
        filled.update(floodfill(w))
    want -= filled

    # Expand the sound until we've seen everything we want.
    while not seen >= want:
        pos = next(positions)
        seen.add(pos)
        max_x = max(max_x, pos[0])
        min_x = min(min_x, pos[0])
        max_y = max(max_y, pos[1])
        min_y = min(min_y, pos[1])
        count += 1

        # Flood fill when we close off an area.
        for next_pos in neighbors(pos):
            if next_pos not in seen:
                seen.update(floodfill(next_pos))

    return count


PARSER = parsers.CoordinatesParser()
TEST_DATA = [
    """\
.......
.......
.......
.#.@...
.......
.......
.......""",
    """\
#..#.......#...
...#...........
...#...........
#######........
...#....#######
...#...@...#...
...#.......#...
...........#...
...........#...
#..........#...
##......#######""",
    """\
................................................................
.........................###.........###........................
....................##...###########.#####......#.......###.....
.........##.............############....####.............##.....
.......######..............#############.###....................
.........##................#############.###.......##...........
...............##...........########....####....................
...............................####.#######...........##........
........................##################...........####.......
....#.........#########################.....##......######......
..............#.##......##....##..##.##...............##........
..............................##....##..........##..............
........####....#################..######...................##..
........###.....###...####..###..##...##.########...............
.................####....###..##.##.##..###....##.....##........
....##...........#######.....##..##..##......#####..........#...
...........##......#########......#....##.######..........#####.
...........##........###########################....#.......#...
.........######............##################.......#...........
...........##.............#########.............................
............#.........#############....................#........
.....#...........##..####......###......##........#.............
.............##................###..........#.....#.............
..................##...........##...................##..........
..........................###.####.####.........................
................#.###########..###.############.#...............
.....#####....###...............................###.............
.....#####...#############......@......#############............
.....#########.###################################.#............
...###########..##.....###################.....##..##...........
...######...#######.##...###.........##...##...###.##...........
.....##.########........#####..###..####.......#.########.......
............#########################################...........
..............#####################################.............
...............................###..............................
................................................................""",
]
TESTS = [
    (1, TEST_DATA[0], 12),
    (2, TEST_DATA[0], 47),
    (3, TEST_DATA[0], 87),
    (3, TEST_DATA[1], 239),
    (3, TEST_DATA[2], 1539),
]


if __name__ == "__main__":
    helpers.run_solution(globals())
